name: tongue_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
      - fastapi
      - uvicorn[standard]
      - opencv-python
      - watchdog
      - python-multipart
      - pydantic-settings
      - python-dotenv
